name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run composer install in docker
        run: bin/manager composer install --no-interaction
      
      - name: Run composer dump autoload
        run: bin/manager composer dump-autoload -o
