name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP with composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: bcmath, ctype, curl, dom, fileinfo, gd, hash, iconv, intl, json, libxml, mbstring, openssl, pcre, pdo_mysql, simplexml, soap, sockets, sodium, tokenizer, xmlwriter, xsl, zip, libxml, openssl
          tools: composer:v2
      
      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction
          composer dump-autoload -o
          
      - name: Run Unit Test
        run: ./vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist
